<?php
return [
    'app' => [
        'base_url' => 'https://YOUR-DOMAIN/ins',
        'timezone' => 'Asia/Baku',
        'session_name' => 'instapilot_session',
        'force_https' => true,
        'encryption_key' => 'CHANGE_THIS_TO_A_32_BYTE_RANDOM_SECRET',
    ],
    'db' => [
        'host' => 'localhost',
        'name' => 'instapilot',
        'user' => 'DB_USER',
        'pass' => 'DB_PASSWORD',
        'charset' => 'utf8mb4',
    ],
    'security' => [
        'csrf_header' => 'X-CSRF-Token',
    ],
    'ai' => [
        'provider' => 'builtin',
        'openai_api_key' => '',
        'openai_model' => 'gpt-4o-mini',
        'gemini_api_key' => '',
        'gemini_model' => 'gemini-2.5-flash',
        'groq_api_key' => '',
        'groq_model' => 'llama-3.3-70b-versatile',
        'gapgpt_api_key' => '',
        'gapgpt_base_url' => '',
        'stability_api_key' => '',
        'deepai_api_key' => '',
        'fal_api_key' => '',
        'kling_api_key' => '',
        'byteplus_api_key' => '',
        'piapi_api_key' => '',
        'maxrouter_api_key' => '',
        'cloudflare_api_token' => '',
        'cloudflare_account_id' => '',
    ],
    'instagram' => [
        'app_id' => '',
        'app_secret' => '',
        'redirect_uri' => 'https://YOUR-DOMAIN/ins/api/instagram/callback',
        'webhook_verify_token' => '',
        'webhook_app_secret' => '',
        'token_encryption_key' => '',
        'graph_base_url' => 'https://graph.instagram.com',
        'oauth_token_url' => 'https://api.instagram.com/oauth/access_token',
        'oauth_authorize_url' => 'https://api.instagram.com/oauth/authorize',
        'scopes' => 'instagram_basic,instagram_content_publish,pages_show_list',
        'refresh_before_days' => 7,
        'media_sync_limit' => 25,
        'media_sync_delay_ms' => 250,
        'media_insights_metrics' => 'views,reach,likes,comments,saved,shares,total_interactions',
        'insights_metrics' => 'reach,accounts_engaged,total_interactions,follower_count,profile_views',
        'insights_period' => 'day',
    ],
];
